using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

namespace Shatter.Core
{
    /// <summary>
    /// A single vertex in the working mesh representation. Kept as a flat struct
    /// (rather than parallel arrays) so clip operations can interpolate a whole
    /// vertex (position + normal + uv + color) in one call.
    /// </summary>
    public struct ShatterVertex
    {
        public Vector3 position;
        public Vector3 normal;
        public Vector2 uv;
        public Color32 color;

        public static ShatterVertex Lerp(ShatterVertex a, ShatterVertex b, float t)
        {
            return new ShatterVertex
            {
                position = Vector3.LerpUnclamped(a.position, b.position, t),
                normal = Vector3.Normalize(Vector3.LerpUnclamped(a.normal, b.normal, t)),
                uv = Vector2.LerpUnclamped(a.uv, b.uv, t),
                color = Color32.Lerp(a.color, b.color, t)
            };
        }
    }

    /// <summary>
    /// One submesh worth of triangles (indices into the shared vertex list) plus
    /// the material it should render with. Interior "cap" faces created by
    /// clipping get their own submesh with the interior material.
    /// </summary>
    public class ShatterSubMesh
    {
        public List<int> triangles = new List<int>();
        public Material material;
        public bool isInteriorFace; // true = generated by a cut, not part of the original surface

        public ShatterSubMesh Clone()
        {
            return new ShatterSubMesh
            {
                triangles = new List<int>(triangles),
                material = material,
                isInteriorFace = isInteriorFace
            };
        }
    }

    /// <summary>
    /// Triangle-list based intermediate mesh representation. This is the format
    /// MeshClipper, VoronoiFracture and RuntimeSlicer all operate on. Converting
    /// to/from UnityEngine.Mesh only happens at the boundaries (import once,
    /// export once per resulting fragment).
    ///
    /// v1 design note: this is intentionally NOT a half-edge / winged-edge
    /// structure. A flat vertex+triangle list is simpler to get correct for the
    /// clipping algorithm, at the cost of O(n) adjacency queries instead of O(1).
    /// If profiling later shows adjacency lookups (e.g. for cap-loop stitching
    /// on large meshes) are a bottleneck, this is the place to upgrade.
    /// </summary>
    public class ShatterMeshData
    {
        public List<ShatterVertex> vertices = new List<ShatterVertex>();
        public List<ShatterSubMesh> subMeshes = new List<ShatterSubMesh>();

        public int VertexCount => vertices.Count;

        public int AddVertex(ShatterVertex v)
        {
            vertices.Add(v);
            return vertices.Count - 1;
        }

        public ShatterSubMesh GetOrCreateSubMesh(Material material, bool isInterior)
        {
            for (int i = 0; i < subMeshes.Count; i++)
            {
                if (subMeshes[i].material == material && subMeshes[i].isInteriorFace == isInterior)
                    return subMeshes[i];
            }

            var sm = new ShatterSubMesh { material = material, isInteriorFace = isInterior };
            subMeshes.Add(sm);
            return sm;
        }

        public ShatterMeshData Clone()
        {
            var clone = new ShatterMeshData
            {
                vertices = new List<ShatterVertex>(vertices)
            };
            foreach (var sm in subMeshes)
                clone.subMeshes.Add(sm.Clone());
            return clone;
        }

        public Bounds ComputeBounds()
        {
            if (vertices.Count == 0) return new Bounds(Vector3.zero, Vector3.zero);
            var b = new Bounds(vertices[0].position, Vector3.zero);
            for (int i = 1; i < vertices.Count; i++)
                b.Encapsulate(vertices[i].position);
            return b;
        }

        // ---------------------------------------------------------------
        // Import from UnityEngine.Mesh
        // ---------------------------------------------------------------
        public static ShatterMeshData FromUnityMesh(Mesh mesh, Material[] materials)
        {
            var data = new ShatterMeshData();

            var positions = mesh.vertices;
            var normals = mesh.normals;
            var uvs = mesh.uv;
            var colors32 = mesh.colors32;

            bool hasNormals = normals != null && normals.Length == positions.Length;
            bool hasUVs = uvs != null && uvs.Length == positions.Length;
            bool hasColors = colors32 != null && colors32.Length == positions.Length;

            data.vertices.Capacity = positions.Length;
            for (int i = 0; i < positions.Length; i++)
            {
                data.vertices.Add(new ShatterVertex
                {
                    position = positions[i],
                    normal = hasNormals ? normals[i] : Vector3.up,
                    uv = hasUVs ? uvs[i] : Vector2.zero,
                    color = hasColors ? colors32[i] : new Color32(255, 255, 255, 255)
                });
            }

            int subMeshCount = mesh.subMeshCount;
            for (int s = 0; s < subMeshCount; s++)
            {
                var tris = mesh.GetTriangles(s);
                Material mat = (materials != null && s < materials.Length) ? materials[s] : null;
                var sm = new ShatterSubMesh
                {
                    material = mat,
                    isInteriorFace = false,
                    triangles = new List<int>(tris)
                };
                data.subMeshes.Add(sm);
            }

            if (!hasNormals)
                data.RecalculateNormals();

            return data;
        }

        // ---------------------------------------------------------------
        // Export to UnityEngine.Mesh
        // ---------------------------------------------------------------
        public Mesh ToUnityMesh(string name = "ShatterFragment")
        {
            var mesh = new Mesh { name = name };

            // Meshes with > 65535 verts need 32-bit indices. Fragments are
            // usually small, but don't silently break on dense source meshes.
            mesh.indexFormat = vertices.Count > 65000
                ? IndexFormat.UInt32
                : IndexFormat.UInt16;

            int vCount = vertices.Count;
            var positions = new Vector3[vCount];
            var normals = new Vector3[vCount];
            var uvs = new Vector2[vCount];
            var colors = new Color32[vCount];

            for (int i = 0; i < vCount; i++)
            {
                var v = vertices[i];
                positions[i] = v.position;
                normals[i] = v.normal;
                uvs[i] = v.uv;
                colors[i] = v.color;
            }

            mesh.vertices = positions;
            mesh.normals = normals;
            mesh.uv = uvs;
            mesh.colors32 = colors;

            mesh.subMeshCount = subMeshes.Count;
            for (int s = 0; s < subMeshes.Count; s++)
                mesh.SetTriangles(subMeshes[s].triangles, s);

            mesh.RecalculateBounds();
            // Normals are computed analytically during clipping/capping, but
            // recalculating tangents is still needed for normal-mapped shaders.
            mesh.RecalculateTangents();

            return mesh;
        }

        /// <summary>Returns the Material[] array matching submesh order, for assigning to a MeshRenderer.</summary>
        public Material[] GetMaterialArray()
        {
            var mats = new Material[subMeshes.Count];
            for (int i = 0; i < subMeshes.Count; i++)
                mats[i] = subMeshes[i].material;
            return mats;
        }

        public void RecalculateNormals()
        {
            var accum = new Vector3[vertices.Count];

            foreach (var sm in subMeshes)
            {
                var tris = sm.triangles;
                for (int i = 0; i < tris.Count; i += 3)
                {
                    int ia = tris[i], ib = tris[i + 1], ic = tris[i + 2];
                    Vector3 pa = vertices[ia].position;
                    Vector3 pb = vertices[ib].position;
                    Vector3 pc = vertices[ic].position;
                    Vector3 faceNormal = Vector3.Cross(pb - pa, pc - pa);

                    accum[ia] += faceNormal;
                    accum[ib] += faceNormal;
                    accum[ic] += faceNormal;
                }
            }

            for (int i = 0; i < vertices.Count; i++)
            {
                var v = vertices[i];
                v.normal = accum[i].sqrMagnitude > 1e-12f ? accum[i].normalized : Vector3.up;
                vertices[i] = v;
            }
        }
    }
}
